// <auto-generated />
using System;
using CQRSArchitecture.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CQRSArchitecture.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240910065829_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CQRSArchitecture.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9d5efcd2-20a2-4240-bfc4-fca69c128ae6"),
                            Description = "Apple's latest flagship smartphone with a ProMotion display and improved cameras",
                            Name = "iPhone 15 Pro",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = new Guid("b8ced01b-d020-425e-91db-8b5ed99cb3a3"),
                            Description = "Dell's high-performance laptop with a 4K InfinityEdge display",
                            Name = "Dell XPS 15",
                            Price = 1899.99m
                        },
                        new
                        {
                            Id = new Guid("56dbf0c2-27f0-4e3c-a435-1aa4ccf8cf5f"),
                            Description = "Sony's top-of-the-line wireless noise-canceling headphones",
                            Name = "Sony WH-1000XM4",
                            Price = 349.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
